/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tcc.Telas;

import tcc.UsuarioDTO;

/**
 *
 * @author usuario
 */
public class MenuUsuario extends javax.swing.JFrame {

    /**
     * Creates new form Perguntas
     * @param usuario
     */
    public MenuUsuario(UsuarioDTO usuario) {
        initComponents();
        usuario = new UsuarioDTO();
        bemVindo.setText("Bem Vindo, " + usuario.getNome()); 
        
    }
    UsuarioDTO usuario;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        niveis = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        facil = new javax.swing.JRadioButton();
        medio = new javax.swing.JRadioButton();
        dificil = new javax.swing.JRadioButton();
        realizarProva = new javax.swing.JButton();
        desempenho = new javax.swing.JButton();
        sair = new javax.swing.JButton();
        bemVindo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 102));

        jLabel2.setFont(new java.awt.Font("Harrington", 0, 18)); // NOI18N
        jLabel2.setText("Escolha o nível desejado para realizar a prova:");

        facil.setBackground(new java.awt.Color(255, 153, 102));
        niveis.add(facil);
        facil.setFont(new java.awt.Font("Harrington", 0, 18)); // NOI18N
        facil.setText("   Fácil");
        facil.setToolTipText("Nível fácil");

        medio.setBackground(new java.awt.Color(255, 153, 102));
        niveis.add(medio);
        medio.setFont(new java.awt.Font("Harrington", 0, 18)); // NOI18N
        medio.setText("   Médio");
        medio.setToolTipText("Nível médio");

        dificil.setBackground(new java.awt.Color(255, 153, 102));
        niveis.add(dificil);
        dificil.setFont(new java.awt.Font("Harrington", 0, 18)); // NOI18N
        dificil.setText("   Difícil");
        dificil.setToolTipText("Nível difícil");

        realizarProva.setFont(new java.awt.Font("Forte", 0, 14)); // NOI18N
        realizarProva.setText("Realizar Prova");
        realizarProva.setToolTipText("Botão para começar a realização da prova");
        realizarProva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                realizarProvaActionPerformed(evt);
            }
        });

        desempenho.setFont(new java.awt.Font("Forte", 0, 14)); // NOI18N
        desempenho.setText("Ver desempenho");
        desempenho.setToolTipText("Botão para verificar o desempenho através dos gráficos");
        desempenho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desempenhoActionPerformed(evt);
            }
        });

        sair.setFont(new java.awt.Font("Forte", 0, 14)); // NOI18N
        sair.setText("Sair");
        sair.setToolTipText("Botão para sair do sistema");
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });

        bemVindo.setEditable(false);
        bemVindo.setBackground(new java.awt.Color(255, 153, 102));
        bemVindo.setFont(new java.awt.Font("Forte", 0, 36)); // NOI18N
        bemVindo.setText("jTextField1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dificil)
                    .addComponent(medio)
                    .addComponent(facil)
                    .addComponent(jLabel2))
                .addContainerGap(109, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 286, Short.MAX_VALUE)
                        .addComponent(sair)
                        .addGap(44, 44, 44))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(bemVindo, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(realizarProva)
                    .addComponent(desempenho))
                .addGap(55, 55, 55))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(desempenho)
                    .addComponent(bemVindo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(jLabel2)
                .addGap(28, 28, 28)
                .addComponent(facil)
                .addGap(34, 34, 34)
                .addComponent(medio)
                .addGap(46, 46, 46)
                .addComponent(dificil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(realizarProva)
                    .addComponent(sair))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed
        Menu menu = new Menu();
        menu.setVisible(true);
        this.setVisible(false);    }//GEN-LAST:event_sairActionPerformed

    private void realizarProvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_realizarProvaActionPerformed
        Pergunta pergunta = new Pergunta(usuario);
        pergunta.setVisible(true);
        this.setVisible(false);    }//GEN-LAST:event_realizarProvaActionPerformed

    private void desempenhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desempenhoActionPerformed
        Desempenho desempenhoUser = new Desempenho();
        desempenhoUser.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_desempenhoActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bemVindo;
    private javax.swing.JButton desempenho;
    private javax.swing.JRadioButton dificil;
    private javax.swing.JRadioButton facil;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton medio;
    private javax.swing.ButtonGroup niveis;
    private javax.swing.JButton realizarProva;
    private javax.swing.JButton sair;
    // End of variables declaration//GEN-END:variables
}
