
package tcc;

import tcc.Telas.Menu;
public class TCC {


    public static void main(String[] args) {
        Menu inicio = new Menu();
        inicio.setVisible(true);
    }
    
//CREATE DATABASE TCC;
//
//USE TCC;
//
//CREATE TABLE CADASTRO(
//ID_USUARIO INT AUTO_INCREMENT PRIMARY KEY,
//NOME VARCHAR(60) NOT NULL,
//SOBRENOME VARCHAR(80) NOT NULL,
//SEXO ENUM('F','M') NOT NULL
//);
//
//CREATE TABLE USUARIO(
//LOGIN VARCHAR(60) PRIMARY KEY,
//SENHA VARCHAR(20) NOT NULL,
//ID_USUARIO INT AUTO_INCREMENT NOT NULL,
//FOREIGN KEY (ID_USUARIO) REFERENCES CADASTRO (ID_USUARIO)
//);
//
//CREATE TABLE PROVA(
//NIVEL_PROVA INT NOT NULL,
//ID_PROVA INT PRIMARY KEY
//);
//
//CREATE TABLE QUESTAO(
//ID_QUESTAO INT PRIMARY KEY,
//AREA INT NOT NULL,
//DESC_ALTERNATIVA_1 VARCHAR(1000) NOT  NULL,
//DESC_ALTERNATIVA_2 VARCHAR(1000) NOT NULL,
//DESC_ALTERNATIVA_3 VARCHAR(1000) NOT NULL,
//DESC_ALTERNATIVA_4 VARCHAR(1000) NOT NULL,
//DESC_ALTERNATIVA_5 VARCHAR(1000) NOT NULL,
//IND_CORRETA INT NOT NULL
//);
//
//CREATE TABLE COMPOSICAO(
//ALTERNATIVA INT NOT NULL,
//ID_PROVA INT NOT NULL,
//ID_QUESTAO INT NOT NULL,
//FOREIGN KEY (ID_PROVA) REFERENCES PROVA (ID_PROVA),
//FOREIGN KEY (ID_QUESTAO) REFERENCES QUESTAO (ID_QUESTAO)
//);
//
//CREATE TABLE AREA_QUESTAO(
//ID_AREA INT PRIMARY KEY,
//NOME VARCHAR(60) NOT NULL
//);
//
//CREATE TABLE FORMULACAO(
//ID_AREA INT NOT NULL,
//ID_PROVA INT NOT NULL,
//FOREIGN KEY (ID_AREA) REFERENCES AREA_QUESTAO (ID_AREA),
//FOREIGN KEY (ID_PROVA) REFERENCES PROVA (ID_PROVA)
//);
    
}
